# Generated by Django 5.1.7 on 2025-05-05 14:50

from django.db import migrations

def create_initial_achievements(apps, schema_editor):
    Achievement = apps.get_model('tasks', 'Achievement')
    
    achievements = [
        # Daily achievements
        {
            'name': 'Early Bird',
            'description': 'Complete 3 tasks in a single day',
            'icon': 'sunrise',
            'requirement_type': 'daily',
            'threshold': 3
        },
        {
            'name': 'Productivity Master',
            'description': 'Complete 5 tasks in a single day',
            'icon': 'star',
            'requirement_type': 'daily',
            'threshold': 5
        },
        {
            'name': 'Overachiever',
            'description': 'Complete 10 tasks in a single day',
            'icon': 'award',
            'requirement_type': 'daily',
            'threshold': 10
        },
        
        # Weekly achievements
        {
            'name': 'Weekly Warrior',
            'description': 'Complete 15 tasks in a week',
            'icon': 'calendar',
            'requirement_type': 'weekly',
            'threshold': 15
        },
        {
            'name': 'Taskmaster',
            'description': 'Complete 30 tasks in a week',
            'icon': 'check-circle',
            'requirement_type': 'weekly',
            'threshold': 30
        },
        
        # Streak achievements
        {
            'name': 'Consistent',
            'description': 'Maintain a 3-day streak of completing tasks',
            'icon': 'trending-up',
            'requirement_type': 'streak',
            'threshold': 3
        },
        {
            'name': 'Dedicated',
            'description': 'Maintain a 7-day streak of completing tasks',
            'icon': 'activity',
            'requirement_type': 'streak',
            'threshold': 7
        },
        {
            'name': 'Unstoppable',
            'description': 'Maintain a 30-day streak of completing tasks',
            'icon': 'zap',
            'requirement_type': 'streak',
            'threshold': 30
        },
        
        # Total achievements
        {
            'name': 'Getting Started',
            'description': 'Complete 10 tasks in total',
            'icon': 'play',
            'requirement_type': 'total',
            'threshold': 10
        },
        {
            'name': 'Task Champion',
            'description': 'Complete 100 tasks in total',
            'icon': 'award',
            'requirement_type': 'total',
            'threshold': 100
        },
        {
            'name': 'Task Legend',
            'description': 'Complete 500 tasks in total',
            'icon': 'trophy',
            'requirement_type': 'total',
            'threshold': 500
        },
    ]
    
    for achievement_data in achievements:
        Achievement.objects.create(**achievement_data)

class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_achievement_alter_userprofile_user_userstats_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_achievements),
    ]
