# Generated by Django 5.1.7 on 2025-05-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_initial_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtask',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharedtask',
            name='is_all_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sharedtask',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_all_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
