# Generated by Django 5.1.7 on 2025-07-03 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_sharedtask_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedtask',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_shared_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedtask',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_shared_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
